### ISSUE TITLE
REQUEST: Configurable user access to "/library/<filename>" route

### ISSUE THREAD

**Issue by danpphil** [ash0ne/docker-pdf-server#24]
I would like to host pdf files that are freely accessible to users on the LAN, but only admins can upload, edit, and delete. I struggled to get NPM to pass the HTTP authentication to the host (which is probably the ideal solution). A temporary fix I found was to comment out line-127 of app.py, which allows users to access files through the "/library/<filename>" route without credentials, but keep credentials for other routes.

REQUEST: It would be fantastic if there was a GUI switch in the "/" route dashboard, or a configurable variable in the docker config / run command, to enable/disable access to files without authentication.

P.s. I think this project is great. I love the minimalist style.

**Comment by ash0ne** [comment]
I'll get it done and release, no problem 😊

**Comment by ash0ne** [comment]
I had in the wishlist to add some sort of user/role management.

**Comment by ash0ne** [comment]
User mangement is now added with support for `reader` user role in version [1.4.0-beta.3](https://hub.docker.com/layers/a0ne/docker-pdf-server/1.4.0-beta.3/images/sha256-c6584d708e16b0a5a6c9754c72f81710d5fed6bff14b002c07c8378d2f8d223a?context=explore) and has been tested.
